[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GPTFF"
version = "0.0.1"
description = "Graph-based Pretrained Transformer Force Field."
authors = [
    {name = "Fankai Xie", email = "fankaixiee@gmail.com"},
    {name = "Tenglong Lu", email = "lutenglongg@gmail.com"}
]
requires-python = ">=3.10"

dependencies = [
    "pymatgen>=2026.5.4",
    "ase>=3.28.0",
    "torch>=2.12.0",
]

[tool.setuptools.packages]
find = { include = ["gptff*"], exclude = ["test*"] }

[project.scripts]
gptff_trainer = "gptff.trainer.trainer:main"

[project.urls]
Homepage = "https://github.com/atomly-materials-research-lab/GPTFF"

[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = ["learn"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
